### ISSUE TITLE
Slow memory allocation and fragmentation occurs in `getInterpolatedData()`

### ISSUE THREAD

**Issue by DLiblik** [rii-mango/Daikon#16]
`getInterpolatedData()` allocates its output array one index at a time, resulting in fragmentation and slow performance.  This can be fixed by pre-allocating the output array.  I did this in PR #11

**Comment by DLiblik** [comment]
For more evidence of how much faster pre-declaring the array size is, please see:

https://jsperf.com/preallocating-array/8

**Comment by rii-mango** [comment]
Nice, fixed.  Thanks for your great additions.
