### ISSUE TITLE
daikon chinese garbled

### ISSUE THREAD

**Issue by hu3402379** [rii-mango/Daikon#20]
hi, @martinezmj ,I have some dicom files, some file's patient name is chinese,  and `daikon.Image.prototype.getPatientName` will return garbled. I do not know how to solve this issue.

The attch file is garbled dcm file for test.
Thanks for your help..

**Comment by nickhingston** [comment]
hi @hu3402379,

Ive just had a look at this issue...

seems Daikon does not support anything other than ascii at the moment.

I have played around with utf-8, big5, gbw and gb18030

none seem to be perfect, but much improved in different ways!

seems others have the same issue: https://github.com/cornerstonejs/dicomParser/issues/89

i have created a branch on my fork
https://github.com/nickhingston/Daikon.git#20-chinese-garbled

worth having a play to see which works best, I cant find out how to auto detect.

one of your files seem to have a different encoding for patientName and address!  but as I cant read Chinese i've no idea what is correct!

to change the encoding set daikon.Utils.utfLabel = "encoding";

the encoding list is here:
https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder

cheers

nick

**Comment by hu3402379** [comment]
@nickhingston ,aha,thanks for your reply.

This question is also my proposal:[cornerstonejs/dicomParser#89](url).
and 'iconv-lite' can solve this issue.

I have tryed to add this lib in daikon, but  I don't know why, I downloaded daikon, and the compilation is not successful. Can you help me to import this library 'iconv-lite' in daikon and then convert the patient name. Then provide me with the compiled daikon.js.

and the '下载4' dicom file's correct Chinese patientName should be 'XU ER ZHU=徐尔铸=XU^ER ZHU'  ,
the 'garbled' file's correct Chinese patient name should be 'ZHANG ZHI HONG(张志红)'.

thanks a lot.

**Comment by nickhingston** [comment]
ah, ok! Seems my unzip or OSX can't cope with Chinese filenames either!

I have pushed an updated version using iconv-lite to that same branch.

It has exactly the same problems as using TextDecoder

using 'gbk' or 'gb18030' i get 
  (0010,0010) Patient Name [XU ER ZHU=$)A徐尔铸-A=XU ER ZHU]
  (0010,1040) Patient Address [鍗楅€氬競鍖楄豹涓滄潙105-101]

& 
  (0010,0010) Patient Name [ZHANG ZHI HONG(张智宏)]

which looks close-ish!

using utf-8:
 (0010,1040) Patient Address [南通市北豪东村105-101]
But, patient names are very garbled in both files!

What were the settings you used to get iconv to work for everything?!
the settings i have pushed to my branch is 'gb18030'

**Comment by nickhingston** [comment]
actually please tell me our postings are OK from a privacy perspective?!

maybe we need to talk directly about this and files/names/address removed...

**Comment by hu3402379** [comment]
@nickhingston  
**1. What were the settings you used to get iconv to work for everything?!**
 'gbk' or 'gb18030' is correct.
> (0010,0010) Patient Name [XU ER ZHU=�$)A徐尔铸�-A=XU ER ZHU]
(0010,0010) Patient Name [ZHANG ZHI HONG(张智宏)]

'utf-8' is correct
>(0010,1040) Patient Address [南通市北豪东村105-101]

'gbk' or 'gb18030' is wrong.
>(0010,1040) Patient Address [鍗楅€氬競鍖楄豹涓滄潙105-101]

I don't know how to use iconv work for every tag yet... It's very strange, each tag is a different encoding.

**2. npm run build error:**
![image](https://user-images.githubusercontent.com/7867792/42623427-6f92bb5a-85f5-11e8-93b4-d36766c3d900.png)

**Comment by hu3402379** [comment]
@nickhingston 

This is not good from a privacy perspective, now, we can delete this information.

**Comment by nickhingston** [comment]
yeah it doesn't make sense to me!  editing to remove personal info...
i guess you should remove the files from cornerstone's parser too!!

**Comment by nickhingston** [comment]
i cant edit your posts...please remove personal info from there.

If you want to contact me directly to continue any conversation that may involve personal info...use my email, i've just made it public on my profile...

**Comment by nickhingston** [comment]
did you do `npm install` first?  can you provide the debug.log file the error message references?

what version of node are you using?

**Comment by hu3402379** [comment]
@nickhingston I have delete the personal info.
so, do you notice the screenshot for npm run build error?

**Comment by nickhingston** [comment]
there is still the patient address (copied from mine) in one of your posts:
```'gbk' or 'gb18030' is wrong.

(0010,1040) Patient Address 
```
yes but it references a debug.log file...

**Comment by hu3402379** [comment]
@nickhingston  I have submit debug.log file in last comment. 
You can help me find the reason of the error.
thanks

**Comment by nickhingston** [comment]
yeah it looks like you havn't run `npm install`

**Comment by hu3402379** [comment]
@nickhingston 
Actually, I did it, and everything looked correct.
![image](https://user-images.githubusercontent.com/7867792/42669352-7d4c1c4a-8687-11e8-9646-fa086c4b4007.png)

**Comment by nickhingston** [comment]
Ah, think I see the problem! Looks like rm failed (load of Chinese after it? )

you need to run this in a unix like shell. As you are using windows - Mingw or something....

**Comment by hu3402379** [comment]
@nickhingston yeah. My environment is windows. I will try it . thanks .

**Comment by hu3402379** [comment]
@nickhingston I have run build in babun. but still get error.
and I have install browserify global.
![image](https://user-images.githubusercontent.com/7867792/42679647-4a484494-86b5-11e8-82b1-c6d4194b23c4.png)

**Comment by nickhingston** [comment]
hmm, seems rm thinks that option is for it, it isn't!

the command is multiline
`rm -rf build; mkdir build; browserify --standalone daikon src/main.js -o build/daikon.js; uglifyjs build/daikon.js -o build/daikon-min.js`

the option should be for browserify...so something odd with your shell still.  So either use a 'proper' OS, or try running these commands separately! 

```
rm -rf build
mkdir build; browserify --standalone daikon src/main.js -o build/daikon.js
uglifyjs build/daikon.js -o build/daikon-min.js
```

**Comment by hu3402379** [comment]
@nickhingston 
I compile commands separately successful, then i replace daikon.js in  rii-mango/papaya and 
run './papaya-builder.sh' faild. if I dont replace, it will be success. 
> rm -rf build
mkdir build
browserify --standalone daikon src/main.js -o build/daikon.js
uglifyjs build/daikon.js -o build/daikon-min.js

![image](https://user-images.githubusercontent.com/7867792/42685731-5ee671d0-86c6-11e8-8bef-14b4ec681eaf.png)

**Comment by hu3402379** [comment]
@nickhingston I have solve it.  Maybe it is Papaya's build ruler error. 'byte' is a reserved word.
in 'daikon.js'
source code:
>// Checks the type of a UTF-8 byte, whether it's ASCII, a leading byte, or a
// continuation byte. If an invalid byte is detected, -2 is returned.
function utf8CheckByte(byte) {
  if (byte <= 0x7F) return 0;else if (byte >> 5 === 0x06) return 2;else if (byte >> 4 === 0x0E) return 3;else if (byte >> 3 === 0x1E) return 4;
  return byte >> 6 === 0x02 ? -1 : -2;
}


Modified code code: 
>// Checks the type of a UTF-8 byte, whether it's ASCII, a leading byte, or a
// continuation byte. If an invalid byte is detected, -2 is returned.
function utf8CheckByte(val) {
    if (val <= 0x7F) {
        return 0;
    } else if (val >> 5 === 0x06) {
        return 2;
    } else if (val >> 4 === 0x0E) {
        return 3;
    } else if (val >> 3 === 0x1E) {
        return 4;
    } else {
        return val >> 6 === 0x02 ? -1 : -2;
    }
}

in addition， 
'dicom-parser' contributor tell me the good news, he has released an npm package ‘dicom-character-set’ to convert all encodings. If you want to, you can try。
> @hu3402379 Good news! I just released an npm package to convert bytes from a DICOM text attribute into a JS string. It'll handle all of the encodings, including with extensions. Check it out here.

**Comment by nickhingston** [comment]
ok, interesting - that makes it a Papaya bug then - Daikon does not have this method!

I suppose the question should be - where should the conversion take place?!  My preference would be in the parser itself.  I which case this Issue still stands...

@martinezmj  what do you think?

will look into dicom-character-set - will certainly be useful for my project (which does not use Papaya).

I am also considering forking off Daikon more 'officially' and calling it something like DICOMgpu.js...because i can't seem to get any response to my PRs on this project, and I think people would like a GPU accelerated javascript DICOM decoder!

**Comment by nickhingston** [comment]
@hu3402379 looked into dicom-character-set.

iconv seems to do a better job for your files than this...

have you any luck with it in the other lib you are using?

**Comment by hu3402379** [comment]
@nickhingston 

Regardless of whether this result is converted from iconv or dicom-character-set, I think the patient name itself should be garbled.

So, the dicom file patient name is not correct coding.

I think both iconv of dicom-character-set is nice to solve chinese garbled.

**Comment by nickhingston** [comment]
OK thanks though I think its the other way around i think the address is not in the specified ('ISO 2022 IR 100\ISO 2022 IR 58) encoding

dicom-character set, doesn't work - iconv does (at least to some degree - it’s a bit ‘cleverer’ at working out unknowns).

I’ll create a PR on using the iconv solution.  Thanks for your input on this.

**Comment by hu3402379** [comment]
@nickhingston 
Do you know about papaya's mpr function, I want to ask you some questions later. Do you mind leaving your email? We communicate via email.

Thanks a lot

**Comment by nickhingston** [comment]
i'm afraid not.  I don't use papaya.

Feel free to email directly - details should be on my profile...

**Comment by nickhingston** [comment]
No not a specific solution, iconv works if you hardcode the format, but there is no obvious way of converting from the DICOM spec to iconv format name.  The other library didn't work for me at all…

**Comment by mipoohh** [comment]
@rii-mango do you have any solution for that? i have similar trouble with korean, and patient name return have added some special symbols
