### ISSUE TITLE
how to get byte value of a tag and some understanding at first glance

### ISSUE THREAD

**Issue by ddbxyrj** [rii-mango/Daikon#25]
first, thank you for this nice program.
for some reason(chinese chart garbled or others). I want to get the byte value(hex or base64 or other types) of an value. Can I just transform the garbled string to byte to get what I want? I can use offset to safely get if, but I definitely not the efficient way.
I can get image bitmap by getInterpretedData() ? The bitmap haven't  been transform by windows width and center? Is there function to apply windows width and center or function build in Papaya(nice name,so cute, or it means something, appearance similar to mango:) ), did function use table lookup to finish it? Is table looking up really faster than calculating? May be there Inflection point for the efficiency. haha. so many question, just for discussion.thank you again.

**Comment by neurolabusc** [comment]
I believe [PR33](https://github.com/rii-mango/Daikon/pull/33) resolves this issue. Reopen with a concrete example if issues persist.
