### ISSUE TITLE
JPEG 2000 lossy decompression problem

### ISSUE THREAD

**Issue by jongo** [rii-mango/Daikon#3]
Magix is JPEG 2000 lossy (1.2.840.10008.1.2.4.91) compressed image set. I have found some issues with image decompression. You can download Magix here: http://www.osirix-viewer.com/datasets/DATA/MAGIX.zip 

![magix](https://cloud.githubusercontent.com/assets/1005993/9810434/09dbe368-5871-11e5-8297-75bcbca85330.png)

For example https://github.com/ivmartel/dwv opens image normally.

**Comment by jongo** [comment]
Hi, I have included latest jpx.js from https://github.com/OHIF/image-JPEG2000 and build daikon. Now JPEG2000 lossy images are now OK.

**Comment by rii-mango** [comment]
Thanks.  I've updated the lib in Daikon.
