### ISSUE TITLE
All tag value is "null"

### ISSUE THREAD

**Issue by specYyt** [rii-mango/Daikon#30]
![image](https://user-images.githubusercontent.com/30110741/58331032-d2d02400-7e6a-11e9-97d9-755cc420ef35.png)
Hello! i did console.log(daikon.Image)，but i saw all value is "null",  and functions like getCols() getRows() getSliceGap()..... get "null", too.   Is it due to "private data"?  The .dcm has been encrypted?  But i can see values by "Sante DICOM Viewer".
Thanks in advance.
![image](https://user-images.githubusercontent.com/30110741/58331279-54c04d00-7e6b-11e9-97f2-92e358d589fd.png)

**Comment by neurolabusc** [comment]
@specYyt  unable to replicate without your sample DICOM.
