### ISSUE TITLE
license.js file references LGPL license for lossless.js but lossless.js has been removed from the repo

### ISSUE THREAD

**Issue by Montoya** [rii-mango/Daikon#34]
lossless.js was removed in this commit: https://github.com/rii-mango/Daikon/commit/0cbf8cc2c927f721fa945d2927dc66fa97694fcf#diff-e8acc63b1e238f3255c900eed37254b8

So I think the reference in license.js should be removed too!

**Comment by neurolabusc** [comment]
@Montoya I assume this has been done, as I see no reference to LGPL in current license. You are correct that some decompression [has moved to a separate library](https://github.com/rii-mango/JPEGLosslessDecoderJS)
