### ISSUE TITLE
Image in negative

### ISSUE THREAD

**Issue by nickhingston** [rii-mango/Daikon#35]
These images are in negative.

Think the relevant tags are:
(0028,0004) Photometric Interpretation [MONOCHROME1]
(0028,1041) Pixel Intensity Relationship Sign [-1]
(2050,0020) PresentationLUT Shape [INVERSE]

I can't seem to find information about what should happen in the case that more than one tag specifies  the pixel values are inverse 
My thoughts were that it would be an XOR relationship, so one inverse would cancel the other.
But have found some DICOMs that (2050,0020) PresentationLUT Shape [INVERSE] & (0028,0004) Photometric Interpretation [MONOCHROME1] which DO require inverting.

Should it just be, invert if one or more of these tags specify inverse...or?

[ISSUE61-56.dcm.zip](https://github.com/rii-mango/Daikon/files/3915916/ISSUE61-56.dcm.zip)
[ISSUE61-55.dcm.zip](https://github.com/rii-mango/Daikon/files/3915867/ISSUE61-55.dcm.zip)

**Comment by martinezmj** [comment]
My guess is that if it's both MONOCHROME1 and INVERSE, that it's still intended to be inverted.  Maybe whatever is writing the header is using multiple tags, knowing how many viewers don't fully support all of these features (and if a viewer doesn't support one, maybe it will support the other).

I've never run into Pixel Intensity Relationship Sign before.... looking at the documentation: "They do not define a transformation intended to be applied to the pixel data for presentation."  so my guess is that one can be ignored.

http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.11.3.html#sect_C.8.11.3.1.2
