### ISSUE TITLE
Cannot open PALETTE COLOR file

### ISSUE THREAD

**Issue by buddamus** [rii-mango/Daikon#43]
Trying to parse the attached anonymized file is throwing an error: can't access property "byteLength", value.buffer is undefined

getPalleteValues http://localhost:4200/daikon.js:41
convertPalette http://localhost:4200/daikon.js:40
getPixelDataBytes http://localhost:4200/daikon.js:40
getRawData http://localhost:4200/daikon.js:40

[US-PAL-8-10x-echo.zip](https://github.com/rii-mango/Daikon/files/4955101/US-PAL-8-10x-echo.zip)

**Comment by neurolabusc** [comment]
DICOM tools are not required to read all transfer syntaxes. Daikon has been developed by users who are interested in MR and CT modalities, so support for UltraSound images is not a priority. Feel free to contribute code if you want to see support extended. This is a community project, and this feature is out of scope for the current developers.

The sample DICOM you provide is from 1994 and exhibits features that were not adopted by any manufacturers.
