### ISSUE TITLE
How convert *.dcm to *.bmp

### ISSUE THREAD

**Issue by dmitrymaslov99** [rii-mango/Daikon#46]
How can i convert images from *.dcm to *.bmp or another format?

**Comment by rudolphpienaar** [comment]
https://github.com/FNNDSC/med2image

**Comment by dmitrymaslov99** [comment]
This is Pyhton, we need node.js (

**Comment by neurolabusc** [comment]
@dmitrymaslov99 Daikon is a library for reading DICOM images, and image conversion is outside the scope of the core project. In theory, you can see how a tool like [NiiVue](https://niivue.github.io/niivue/) can use Daikon to open an image and then can save this as a bitmap. However, most medical images have a high dynamic range (e.g. 16-bit scalar values) and most bitmap formats are designed for 256 levels of gray (e.g. even 32-bit RGBA has 256 levels of gray), so you need to choose the brightness and contrast (window width and window center in DICOM speak). This makes a generalized solution a bit tricky. Again, you can see how NiiVue solves this, with a `robust range` for MR scans and different color tables for CT scans (e.g. bones, airways, kidneys, etc).
