### ISSUE TITLE
Cant open encapsulated PDF.

### ISSUE THREAD

**Issue by hilmican-yuksel** [rii-mango/Daikon#48]
getEncapsulatedData() function is looking for pixel data. But in my case, dicom file doesnt have pixel data. And i think daikon doesnt read Encapsulated Document tag. How can I open or read this pdf data with daikon.js

**Comment by neurolabusc** [comment]
@hilmican-yuksel I am unaware of a PDF-based [DICOM transfer syntax](https://www.dicomlibrary.com/dicom/transfer-syntax/). DICOM only requires tools to support the uncompressed transfer syntax. While Daikon supports the most popular  forms of data compression, supporting rare and non-standard encapsulated data is beyond the scope of this project.

**Comment by hilmican-yuksel** [comment]
@neurolabusc Thanks for your reply.
