### ISSUE TITLE
Need to bump version and provide a new release

### ISSUE THREAD

**Issue by hanayik** [rii-mango/Daikon#56]
@rii-mango , some Github actions tests and updated dependencies maintenance tasks were done by @jens-ox. We need to build and publish a new release to NPM. However, I noticed there is now an `esbuild` and a `build` script. Which are you calling prior to publishing? I think we should also update the `README.md` to reflect the order of operations for publishing a new release.

**Comment by rii-mango** [comment]
I think esbuild should be the recommended script for building and release.  I reverted to build when I was trying to add xss protection to Papaya and couldn't build Papaya using the new esbuild-made Daikon.  At the time I thought there was an issue with the esbuild version, but now it's clear that it was just Papaya-Builder being unable to handle the modern esbuild formats.
