### ISSUE TITLE
jpeg-lossless-decoder-js version 2.1.0 is broken please lock jpeg-lossless-decoder-js to 2.0.7

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [rii-mango/Daikon#58]
jpeg-lossless-decoder-js version 2.1.0 is broken please lock jpeg-lossless-decoder-js to 2.0.7

work around:

In package.json
```
"overrides": {
    "daikon": {
      "jpeg-lossless-decoder-js": "2.0.7"
    }
  }
  ```

**Comment by tudor33sud** [comment]
is someone still maintaining daikon? I encountered the same issue.. we either wait for jpeg lossless decoder to fix it or we should fix it here..

**Comment by rii-mango** [comment]
I've changed package.json dependancies to use "2.0.7" instead of "^2.0.7" on jpeg-lossless-decoder-js.  How does that look on your end?

**Comment by tudor33sud** [comment]
I think that should suffice, however at least for me I need a release on npm channel so that I can update my daikon version properly. Do you think you could do that ? As far as I can see, the package is still the old one released 9 months ago.

**Comment by rii-mango** [comment]
Added v1.2.46 in GitHub and npm

**Comment by tudor33sud** [comment]
thanks a lot for your cooperation!
