### ISSUE TITLE
Save changes into a Dicom

### ISSUE THREAD

**Issue by levibn** [rii-mango/Daikon#8]
In my work I need to anonymize dicoms file as we move it through internet and if 
been catch must NOT contain certain informations about patient. So I wanna know if this could be done with this amazing tool, Daikon.
Thanks!

**Comment by martinezmj** [comment]
Daikon currently only reads the data.  It does not support saving it back to disk.  If all you need to do is read in and anonymize the data, then yes that is something that can easily be added.

**Comment by rii-mango** [comment]
Archiving this.  Out of scope for now.
